name: example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_core: ^0.5.0+1
  cloud_firestore: ^0.14.1+3
  provider: ^4.3.2+2



dev_dependencies:
  flutter_test:
    sdk: flutter
  dash_chat:
    path: ../
flutter:
  uses-material-design: true

